export default {
  GET_GROUPS: 'EVENT_GET_GROUPS',
  GET_SERIES: 'EVENT_GET_SERIES',
  API_SET_VALUE: 'EVENT_API_SET_VALUE',
  LOGIN: 'EVENT_LOGIN',
  EXIT: 'EXIT',
  WINDOW_MAXIMIZE: 'WINDOW_MAXIMIZE',
  WINDOW_MINIMIZE: 'WINDOW_MINIMIZE',
};
