export default {
  GET_GROUPS: 'EVENT_GET_GROUPS',
  GET_SERIES: 'EVENT_GET_SERIES',
  GET_GROUP_FILTERS: 'EVENT_GET_GROUP_FILTERS',
  API_SET_VALUE: 'EVENT_API_SET_VALUE',
  LOGIN: 'EVENT_LOGIN',
  LOGIN_IMAGE: 'EVENT_LOGIN_IMAGE',
  EXIT: 'EXIT',
  WINDOW_MAXIMIZE: 'WINDOW_MAXIMIZE',
  WINDOW_MINIMIZE: 'WINDOW_MINIMIZE',
  GET_DASHBOARD: 'EVENT_GET_DASHBOARD'
};
